name: Build Check

on:
  pull_request:
    branches:
      - main
      - feature
      - develop

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Download Repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Frontend-Install Dependencies
        run: npm install
        working-directory: ./frontend

      - name: Frontend-Build
        run: npm run build
        working-directory: ./frontend

      - name: Backend-Install Dependencies
        run: npm install
        working-directory: ./backend

      - name: Backend-Build
        run: npm run build
        working-directory: ./backend
